### ISSUE TITLE
Service does not install

### ISSUE THREAD

**Issue by diomenas** [perfwatcher/collectm#4]
I am attempting to install this on a Win Svr 2008 R2 SP1 Server and when you run the installer it does not install the service. 

If I attempt to run node on service.js with the arg of "install" it reports that the service is already installed.  If I do anything other than "install" or "installandstart" it reports nothing and the service is not installed.

**Comment by feraudet** [comment]
I already had this issue last summer, I don't remember if I had to reboot to see the service as installed or if it was solved using node service.js uninstall / install a couple of time. I didn't figured out if it was a windows 2008 or a node issue

**Comment by ymettier** [comment]
Hello,

We have had problems too (with other versions of Windows).
We solved the problem by getting rid of node-windows module (not for that module itself, but because of its dependancies).

So we rewrote all the service layer (now using nssm).

Please tell us if Collectm-1.4.0 works better for you.

Regards
Yves

**Comment by ymettier** [comment]
Commit 273b38ed1250b09b710794144bb8c97890b2def5 (version 1.4.0) and previous commits should have fixed the problem.
We consider this problem as obsolete. If you have a similar problem, please ensure that you are running a recent version of Collectm and then open a new issue.
