### ISSUE TITLE
collectdCompat: some metric categories don't seem to get collected

### ISSUE THREAD

**Issue by dimrozakis** [perfwatcher/collectm#6]
I'm trying out collectm on a windows 2008 server. In collectdCompat.js I see that it collects cpu, mem, df, disk, interface, load, uptime, process and swap. However in the collectd server receiving the data sent from collectm, I only get disk, df, cpu and interface. Am I missing something here?

**Comment by ymettier** [comment]
1/ wait 5 or 10 minutes more (worked most of the times)
2/ if still missing, get https://github.com/perfwatcher/collectd-pw/blob/release/5.4.0/src/types-perfwatcher.db and add it in your collectd server configuration.
My /etc/collectd.conf contains those lines : 

TypesDB     "/usr/share/collectd/types.db"
TypesDB     "/usr/share/collectd/types-perfwatcher.db"

Does any of those 2 solutions work ?

Regards,
Yves

**Comment by dimrozakis** [comment]
Hey Yves,
Waiting didn't change anything, but I started getting all the missing metrics once I added types-perfwatcher.db to my collectd server's config. Thanks.

**Comment by ymettier** [comment]
Hello,

Glad to hear that it works for you.

However, I just read the code again, with all my attention regarding Collectd types.db and Perfwatcher types-perfwatcher.db and there is no link to types-perfwatcher.db.

Collectd side :
I think that something else was going wrong and the restart (to take types-perfwatcher.db into account) fixed it. Or maybe you did not even had problems with Collectd ?

Perfwatcher side : 
Perfwatcher won't work well if types-perfwatcher.db is not installed with collectd-pw.

Because it works for you and there is no reason that not to work anywhere else, I keep the issue closed.

Thanks for your feedback.

Regards,
Yves
